[ids]
*

[main]
meta = layer(meta)

[meta]
w = A-f4

[meta+shift]
# 'b' - Standard Brave with Wayland flags
b = command(sudo -u ashc0d DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemd-run --user --machine=ashc0d@.host /usr/bin/brave-browser --enable-features=TouchpadOverscrollHistoryNavigation,UseOzonePlatform --ozone-platform=wayland)

# 'm' - Brave App
m = command(sudo -u ashc0d DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemd-run --user --machine=ashc0d@.host /usr/bin/brave-browser --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod)

# 'p' - Bitwarden
p = command(sudo -u ashc0d DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemd-run --user --machine=ashc0d@.host bitwarden)

# Copilot Key (f23)
f23 = command(sudo -u ashc0d DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemd-run --user --machine=ashc0d@.host /usr/bin/brave-browser --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod)
