[ids]
*

[main]
# This handles the manual Win+Shift+M
# We use the 'M' inside a meta+shift layer
[meta+shift]
m = command(export WAYLAND_DISPLAY=wayland-0; export XDG_RUNTIME_DIR=/run/user/1000; sudo -u ashc0d /opt/brave.com/brave/brave-browser --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod)
# Copilot Key
f23 = command(export WAYLAND_DISPLAY=wayland-0; export XDG_RUNTIME_DIR=/run/user/1000; sudo -u ashc0d /opt/brave.com/brave/brave-browser --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod)
